Vagrant.configure("2") do |config|
  config.vm.box = "fedora/25-cloud-base"
  config.vm.box_version = "20161122"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "shell", inline: <<-SHELL
    echo "vagrant:vagrant" | chpasswd

    rpm --import https://packages.microsoft.com/keys/microsoft.asc
    sh -c 'echo -e "[packages-microsoft-com-prod]\nname=packages-microsoft-com-prod \nbaseurl=https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/dotnetdev.repo'
    dnf update -y
    dnf install -y libunwind libicu
    dnf install -y dotnet-sdk-2.0.0

    dotnet --version
  SHELL
end