---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
platforms:
  # This list should be roughly kept in sync with the list of supported OSes described at
  # https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md,
  # and/or the list of OSes for which .NET Core builds packages, as seen at
  # https://dotnet.microsoft.com/download/linux-package-manager/sdk-current
  # There are no Docker images for RHEL, so we can't test that.
  # Not sure about Linux Mint/Suse Enterprise Linux docker images, so they are skipped for now.
  #
  # OpenSUSE uses zypper as the package manager, but zypper doesn't seem to
  # handle RPM boolean dependencies. Installing the rpm package will fail like
  # this:
  #
  # > Problem: nothing provides (openssl-libs or libopenssl1_1 or libopenssl_1_0_0) >=  needed by self-contained-app-1.0.0-0.x86_64
  #
  # You can manually install the package using rpm -i {path_to_rpm}, though, but Ansible doesn't provide
  # a good way to do that.
  #
  - name: ubuntu.16.04
    image: ubuntu:16.04
  - name: ubuntu.18.04
    image: ubuntu:18.04
  - name: ubuntu.20.04
    image: ubuntu:20.04
  # Fails with: Package 'python-apt' has no installation candidate
  # - name: ubuntu.21.10
  #   image: ubuntu:21.10
  - name: debian.9
    image: debian:9
  - name: debian.10
    image: debian:10
  # Fails with: Package 'python-apt' has no installation candidate
  # - name: debian.11
  #   image: debian:11
  - name: fedora.31
    image: fedora:31
  - name: fedora.32
    image: fedora:32
  - name: fedora.33
    image: fedora:33
  - name: centos.7
    image: centos:7
  - name: centos.8
    image: centos:8
  - name: ol.7
    image: oraclelinux:7
  - name: ol.8
    image: oraclelinux:8
  # There's an issue with self-contained apps on OpenSUSE 15.0 (see above), so that's
  # disabled for now.
  # - name: opensuse.15.0
  #   image: opensuse/leap:15.0

provisioner:
  name: ansible
  lint: |
    set -e
    ansible-lint
  inventory:
    host_vars:
      fedora.30:
        # https://github.com/ansible/ansible/issues/54855
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: default
verifier:
  name: testinfra
  options:
    junitxml: pytest.xml
  lint: |
    set -e
    flake8
